### ISSUE TITLE
C6H28N21O28P2S3

### ISSUE THREAD

**Issue by tomas-pluskal** [zmzhang/PFG#4]
Hi,

I ran 

```
PFG test -m 1000 -t 5  --C 2-100 --H 2-100 --N 2-40 --O 2-70 --S 2-5 --P 2-5 -r
```

And I noticed C6H28N21O28P2S3 was among the results.

According to http://www.sisweb.com/referenc/tools/exactmass.htm, the formula C6H28N21O28P2S3 has an exact mass of 1000.005016 Da, so the mass error should be greater than 5 ppm and it should not be included. The PFG reports the mass of this formula as 1000.005000 (error -4.999492). Is this a bug?

Thanks,

Tomas

**Comment by zmzhang** [comment]
Hi Tomas:

It is the bug of exact mass. The exact mass calculator calculates mass of formula with Javascript.
You can download [exactmass.js](http://www.sisweb.com/referenc/tools/exactmass.js) and read the source code of it. The precision of atomic mass of exactmass is only the sixth decimal place. Moreover, there are round error for O, S and P.

The atomic mass of PFG is  in accordance with [**_The Ame2003 atomic mass evaluation_**](http://www.sciencedirect.com/science/article/pii/S0375947403018098). In future, we will update the atomic mass of PFG to [**_The Ame2012 atomic mass evaluation_**](http://iopscience.iop.org/1674-1137/36/12/002).

The following figure is comparison on atomic mass of C, H, O, N, S and P between exact mass calculator  and PFG.

![comparison](https://cloud.githubusercontent.com/assets/6937141/17430506/21e1a254-5b27-11e6-8984-df83684fa910.png)

Regards
Zhimin

**Comment by tomas-pluskal** [comment]
Hi Zhimin,

I noticed some differences between the mass values in the Ame2003 paper and the mass values used in PFG. For example 32S mass in Ame2003 is 31.97207100 Da, but [your code](https://github.com/zmzhang/PFG/blob/master/elements.cpp#L182) has 31.972070689999999 Da. What is the reason behind these differences?

**Comment by zmzhang** [comment]
We follow  [mMass](http://pubs.acs.org/doi/abs/10.1021/ac100818g), and it is consistent with AME2003 if you round the mass values properly.   The mass values of mMass has more decimal place than AME2003 .

Please see the [code ](https://github.com/wolski/mspy/blob/master/mspy/blocks.py)of mMass
