### ISSUE TITLE
Usability improvements

### ISSUE THREAD

**Issue by tomas-pluskal** [zmzhang/PFG#6]
This is not a bug, but a feature request.

1) It would be great if we could specify the output filename as a parameter, and if no filename is specified, print the results to stdout.

2) It would be great if we could specify the tolerance units (ppm or Da) as a parameter. I see it is already [implemented in the code](https://github.com/zmzhang/PFG/blob/master/formula.cpp#L83), so it is just a matter of adding the parameter.

**Comment by zmzhang** [comment]
Hi Tomas:

Now you can specify the output file by -f .
The tolerance unit can be set by -u.
PFG test -m 46.005480 **-u ppm** -t 10  --C 0-20 --H 0-40 --O 0-5 --N 0-5

![stdout](https://cloud.githubusercontent.com/assets/6937141/17452534/82c7dc16-5ba2-11e6-86c4-d320c8139f4a.png)

Regards
Zhimin
