### ISSUE TITLE
Printing formulas

### ISSUE THREAD

**Issue by tomas-pluskal** [zmzhang/PFG#7]
When the formulas are [printed](https://github.com/zmzhang/PFG/blob/master/formula.cpp#L228), the number is always printed for each element, even if it is 1. This results in somewhat unnatural output such as C1H2O2 (other software tools would report CH2O2 instead). Could you avoid printing the number if == 1?

**Comment by tomas-pluskal** [comment]
```
                        const unsigned int elnum = p_result->data[i*elcount + j];
                        if(elnum !=0)
                        {
                                strncat(temp, compositions[j], strlen(compositions[j]));
                                if (elnum != 1)
                                {
                                        sprintf(s, "%d",p_result->data[i*elcount + j]);
                                        strncat(temp, s, strlen(s));
                                }
                        }
```

**Comment by zmzhang** [comment]
Hi Tomas:

Your code has been merged into PFG.
And it works well.

PFG test -m 46.005480 -t 10  --C 0-20 --H 0-40 --O 0-5 --N 0-5
![print](https://cloud.githubusercontent.com/assets/6937141/17451952/819dd71e-5b9d-11e6-8792-db599f61b8e6.png)

Thanks
Zhimin
